name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
    DB_CONNECTION: mysql
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
    DB_DATABASE: test
    DB_USERNAME: root
    DB_PASSWORD: root
jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services: 
       mysql: 
         image: mysql:8.0
         ports:
           - 3306/tcp
         env: 
           MYSQL_DATABASE: ${{ env.DB_DATABASE }}
           MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
         options: >-
           --name=mysql
           --health-cmd="mysqladmin ping"
           --health-interval=10s
           --health-timeout=5s
           --health-retries=5                         
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Roda as migrations e testes
      run: |
          php artisan migrate --force
          php artisan test
